IF
    Global("ZDAuctionTrigger", "GLOBAL", 1)
THEN
    RESPONSE #100
        SetGlobal("ZDAuctionTrigger", "GLOBAL", 1)
        // Actioneer
        CreateCreature("zdauctio", [1928.3425], N)
        // Crowd
        CreateCreature("NOBLE1", [1748.3319], S)
        CreateCreature("NOBLE2", [1805.3313], S)
        CreateCreature("NOBL4", [1874.3320], S)
        CreateCreature("NOBL5", [1933.3324], S)
        CreateCreature("NOBL6", [1976.3319], S)
        CreateCreature("NOBLEW1", [2000. 3319], S)
        CreateCreature("NOBLEW2", [2126.331], S)
        Continue()
END

IF
    Global("ZDAuctionTrigger", "GLOBAL", 10)
THEN
    RESPONSE #100
        SetGlobal("ZDAuctionTrigger", "GLOBAL", 99)
        // Actioneer
        ActionOverride("zdauctio", DestroySelf())
        Continue()
END
