IF
  True()
THEN
  RESPONSE #100
    CutSceneID(Player1)
    ClearAllActions()
    SetGlobal("ZDBAE1_CUTSCENE_BREAKABLE","GLOBAL",1)
    SetCutSceneBreakable(TRUE)
    // NOBLE 1
    DisplayStringPoint([2453.1575],@101) /* ~A drow? Here?~ */
    Wait(1)
    DisplayStringHead("Announcer",@102) /* ~WHAT?! Security, Security!~ */
    Wait(1)
    SetCutSceneBreakable(FALSE)
    IncrementGlobal("ZDBAE1_CUTSCENE_BREAKABLE","GLOBAL",1)
    CreateCreature("copamb02",[1850.1507],SSE)
    ActionOverride("copamb02",Attack("ZDBAE"))
    ActionOverride("copamb02",MoveToPoint([2080.1520]))
    SmallWait(5)
    CreateCreature("copamb02",[1878.1500],SSE)
    ActionOverride("copamb02",Attack("ZDBAE"))
    ActionOverride("copamb02",MoveToPoint([2108.1510]))
    SmallWait(5)
    CreateCreature("copamb02",[1890.1578],SSE)
    ActionOverride("copamb02",Attack("ZDBAE"))
    ActionOverride("copamb02",MoveToPoint([2147.1484]))
    SmallWait(5)
    SetCutSceneBreakable(TRUE)
    Wait(2)
    // NOBLE 2
    DisplayStringPoint([2385.1533],@103) /* ~Burn the drow!~ */
    Wait(2)
    DisplayStringHead("Frankie",@104) /* ~Kill the drow!~ */
    Wait(2)
    DisplayStringHead("ZDBAE",@105) /* ~Good people I uh... Lets be reasonable about this!~ */
    Wait(2)
    SetCutSceneBreakable(FALSE)
    ActionOverride("zdfranki", DestroySelf())
    SetGlobal("ZDBAE1_CUTSCENE_BREAKABLE","GLOBAL",0)
    EndCutSceneMode()
    AddJournalEntry(@101,INFO)
    ActionOverride("ZDBAE",StartDialogueNoSet([PC]))
END
