IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        ClearAllActions()
        SetGlobal("ZDBAE1_CUTSCENE_BREAKABLE", "GLOBAL", 1)
        SetCutSceneBreakable(TRUE)
        ActionOverride("ZDBAE", ForceSpell("ZDBAE", FLASHY_4))
        SmallWait(5)
        // NOBLE 1
        DisplayStringPoint([2453.1575], @101)  /* A drow? Here? */
        Wait(2)
        DisplayStringHead("Announcer", @102)  /* WHAT?! Security, Security! */
        Wait(2)
        SetCutSceneBreakable(FALSE)
        IncrementGlobal("ZDBAE1_CUTSCENE_BREAKABLE", "GLOBAL", 1)
        CreateCreature("copamb02", [1850.1507], SSE)
        ActionOverride("copamb02", Attack("ZDBAE"))
        SmallWait(5)
        CreateCreature("copamb02", [1878.1500], SSE)
        ActionOverride("copamb02", Attack("ZDBAE"))
        SmallWait(5)
        CreateCreature("copamb02", [1890.1578], SSE)
        ActionOverride("copamb02", Attack("ZDBAE"))
        SmallWait(5)
        SetCutSceneBreakable(TRUE)
        Wait(2)
        // NOBLE 2
        DisplayStringPoint([2385.1533], @103)  /* Burn the drow! */
        Wait(2)
        DisplayStringHead("Frankie", @104)  /* Kill the drow! */
        Wait(2)
        DisplayStringWait("ZDBAE", @112)  /* Oh my! Tough crowd. */
        ActionOverride("ZDBAE", ReallyForceSpellRES("SPWI408", "ZDBAE"))
        ActionOverride("ZDBAE", ReallyForceSpellRES("SPWI212", "ZDBAE"))
        ActionOverride("ZDBAE", Attack("copamb02"))
        SetCutSceneBreakable(FALSE)
        ActionOverride("zdfranki", DestroySelf())
        SetGlobal("ZDBAE1_CUTSCENE_BREAKABLE", "GLOBAL", 0)
        EndCutSceneMode()
        AddJournalEntry(@101, INFO)
        ActionOverride("ZDBAE", StartDialogueNoSet([PC]))
END
