name: 'checks'
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: nixbuild/nix-quick-install-action@master
      - name: nixcache
        uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G
      - name: pre-commit
        shell: 'nix develop -c bash -e {0}'
        run: env HK_FIX=0 hk run pre-commit --all --no-fail-fast --stash none
